"""Add status to Room

Revision ID: 969f9f59cef4
Revises: dfd9da74ceba
Create Date: 2025-06-24 14:31:57.786082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969f9f59cef4'
down_revision = 'dfd9da74ceba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
